version: '3.8'

networks:
  vpn-bypass:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: vpn-bypass
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:
  vpn-monitor:
    build: .
    container_name: vpn-monitor
    restart: unless-stopped
    
    # Required for VPN operations
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    
    # Mount configuration
    volumes:
      - ./.env:/app/.env:ro
      - vpn-logs:/var/log/vpn-monitor
      - /lib/modules:/lib/modules:ro
    
    # Use custom bridge network (better for WSL2)
    networks:
      vpn-bypass:
        ipv4_address: 172.30.0.10
    
    # DNS configuration to ensure proper resolution
    dns:
      - 8.8.8.8
      - 1.1.1.1
    
    # Environment variables (can be overridden by .env file)
    environment:
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "/app/vpn_monitor.py", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  vpn-logs: